server:
  port: 8087
  servlet:
    session:
      timeout: 28800s

spring:
    data:
      rest:
        base-path: /api
    datasource:
        url: jdbc:mysql://localhost:3306/taskemployer?verifyservercertificate=false&useSSL=false&characterEncoding=utf8&characterSetResults=utf8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
      cache: false
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    session:
#     timeout: ONE_MINUTE_IN_SECONDS
